name: CI

on:
  workflow_dispatch: {}
  push:
    branches:
      - main
    paths-ignore:
      - ".git**"
  pull_request:

jobs:
  lint-ruby:
    name: Lint Ruby
    uses: publishing-platform/publishing-platform-infrastructure/.github/workflows/rubocop.yml@main

  test-ruby:
    name: Test Ruby
    runs-on: ubuntu-latest
    steps:
      - name: Setup Postgres
        id: setup-postgres
        uses: publishing-platform/publishing-platform-infrastructure/.github/actions/setup-postgres@main

      - name: Checkout repository
        uses: actions/checkout@v4   

      - name: Checkout Publishing API (for Content Schemas)
        uses: actions/checkout@v4
        with:
          repository: publishing-platform/publishing-api
          ref: main
          path: vendor/publishing-api      
          token: ${{ secrets.PUBLISHING_PLATFORM_CI_GITHUB_API_TOKEN }}                   

      - name: Setup Ruby
        uses: ruby/setup-ruby@v1
        with:
          bundler-cache: true

      - name: Initialize database
        env:
          RAILS_ENV: test
          TEST_DATABASE_URL: ${{ steps.setup-postgres.outputs.db-url }}
        run: bundle exec rails db:setup     

      - name: Run RSpec
        env:
          RAILS_ENV: test
          TEST_DATABASE_URL: ${{ steps.setup-postgres.outputs.db-url }}
          PUBLISHING_PLATFORM_CONTENT_SCHEMAS_PATH: vendor/publishing-api/content_schemas
        run: bundle exec rake spec